# Generated by Django 5.0.6 on 2024-05-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Ishchilar | Workers',
                'verbose_name_plural': 'Ishchichi | Worker',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('KEL', 'KELADI'), ('ULA', 'ULANILMADI'), ('QOL', 'QOLDIRILDI'), ('KEM', 'KEMIDI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.worker'),
        ),
    ]
