# Generated by Django 5.0.6 on 2024-05-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('KELADI', 'KELADI'), ('ULANILMADI', 'ULANILMADI'), ('QOLDIRILDI', 'QOLDIRILDI'), ('KEMIDI', 'KEMIDI')], max_length=20, null=True),
        ),
    ]
