# Generated by Django 5.0.6 on 2024-05-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Mijoz ', 'verbose_name_plural': 'Mijozlar '},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Ishchi ', 'verbose_name_plural': 'Ishchilar '},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='FIO',
        ),
    ]
