# Generated by Django 5.0.6 on 2024-05-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_rename_f_i_o_client_f_i_o_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='updated_at',
            new_name='tekshirilgan_vaqti',
        ),
    ]
